### ISSUE TITLE
Changing the desired rocket angle has no effect.

### ISSUE THREAD

**Issue by hammaal** [FeliNUx42/PID-Simulation#1]
Even if I change the desired rocket angle, the simulation still solves to a desired rocket angle of 0.

**Comment by FeliNUx42** [comment]
Oh sorry, I haven't implemented that yet. I'll try to do it asap (should be pretty easy)!

**Comment by hammaal** [comment]
Hey. I would love to see your solution. I tried going through and changing/adding things to make it work but I did not manage to get the rocket to recognize the desired angle. The graphs did later on show the new desired angle though. At some point I managed to break the entire thing.

Really nice code by the way. It was quite easy to understand going through it. Just my lack of knowledge could not get it working.

**Comment by hammaal** [comment]
Hey. I would love to see your solution. I tried going through and changing/adding things to make it work but I did not manage to get the rocket to recognize the desired angle. The graphs did later on show the new desired angle though. At some point I managed to break the entire thing.

Really nice code by the way. It was quite easy to understand going through it. Just my lack of knowledge could not get it working.

As you can see I am new to github too. Accidentally closed the issue. My bad

**Comment by hammaal** [comment]
Hey. I would love to see your solution. I tried going through and changing/adding things to make it work but I did not manage to get the rocket to recognize the desired angle. The graphs did later on show the new desired angle though. At some point I managed to break the entire thing.

Really nice code by the way. It was quite easy to understand going through it. Just my lack of knowledge could not get it working.

As you can see I am new to github too. Accidentally closed the issue. My bad

**Comment by FeliNUx42** [comment]
Ok, I added it. Now it should work.
If you want to see which modifications I made, you can look at this commit: 6870bc70c61195ea753435acfc6e6f10365852f1

**Comment by hammaal** [comment]
Thanks. That was fast.
